/** @format */

import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { ToastContainer } from 'react-toastify';
import StoreProvider from './components/StoreProvider';
import AuthWrapper from './components/AuthWrapper';
import { PersistGate } from 'redux-persist/integration/react';
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Velofolio',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
       <ToastContainer />
          <StoreProvider>
   {/* <AuthWrapper> */}
    {children}

   {/* </AuthWrapper> */}
         
          </StoreProvider>
        </body>
    </html>
  );
}
